### ISSUE TITLE
How to return status ID of sent tweet?

### ISSUE THREAD

**Issue by mwoolweaver** [choldgraf/threader#2]
i haven't been able to figure this out and i've looked everywhere i know to look, maybe i'm missing something?

**Comment by choldgraf** [comment]
I believe the tweet ID is stored in an attribute `tweet_ids_`

https://github.com/choldgraf/threader/blob/master/threader/thread.py#L112

Sorry for the lack of docs - this was a quick project and I'm not spending a ton of time maintaining it  :-/

**Comment by mwoolweaver** [comment]
That worked perfectly!!! Thank you for the help!

https://twitter.com/voucher_swap/status/1153533651478634502 <-- Threader in action

**Comment by choldgraf** [comment]
Wahoo! 😊

**Comment by mwoolweaver** [comment]
if i was better at this i could've figured that out probably...
